### ISSUE TITLE
[12.0] Is there an addon to define the status of survey_user_input to expired?

### ISSUE THREAD

**Issue by victoralmau** [OCA/survey#38]
Before proposing to upload a new addon called: **survey_user_input_expired** that we already have developed, I would like to know if something similar exists.

This addon would replace the state of the survey responses to define a new state called: _expired_
In addition, using a cron that runs once a day, responses with expired status are auto-defined with respect to all those that have a deadline defined.

Thank you very much.

**Comment by pedrobaeza** [comment]
I don't know any, but what is the aim of it?

**Comment by victoralmau** [comment]
The functionality that I suggest would be a basis for other addons, for example suppose we want to do a survey manually by calling by phone (survey A) and if it could not be done to send them by email with another survey (survey B). 

The idea of ​​this is to auto create survey_user_input for partner_id for survey A that we want and set an expiration date so that they only expire if we have not manually completed them when calling by phone. 
On the other hand, another functionality would make that for all the expired responses, create another survey_user_input for survey B and send the client the link to carry it out by email.

**Comment by pedrobaeza** [comment]
Sorry, not sure to understand the goal, but it seems similar to rating modules for catching answers from customers.
