### ISSUE TITLE
Survey filled in by invitation Does not show in partner form. 

### ISSUE THREAD

**Issue by maria2233** [OCA/survey#9]
I've invited a partner to fill in a Survey. 
Results is in menu marketing under Surveys but does not show in partner form.

**Comment by rafaelbn** [comment]
@maria2233 what do you mean by "partner form"?
Have you tried https://github.com/OCA/survey/tree/8.0/partner_survey?

**Comment by maria2233** [comment]
Hello Rafaelbn thanks for the comment. what i mean is this:
i installed the odoo app "partner _survey". then i made a survey. and after testing it, i put it live.
i invited a client to take the survey. and he made the survey. 
now this is what i get as result when i look at the client card.  ( i tought this is another name for ""partner form" excuse me if i am wrong.).  nothing here.   you can see it here. http://www.salonpro.nl/eyeforyou/surveyodoo.png

**Comment by rafaelbn** [comment]
I  test in the same way and this is my result

![26-08-2015 20-49-36](https://cloud.githubusercontent.com/assets/8736623/9502878/14453e9c-4c34-11e5-819b-386e05680bb0.png)

Go to Marketing - Surveys - Answers and check the answer has a Partner, if not it will not appears

![26-08-2015 20-51-02](https://cloud.githubusercontent.com/assets/8736623/9502934/5856f2b0-4c34-11e5-8372-66b4ddd5e6b5.png)

**Comment by maria2233** [comment]
Ow. okay. i see what happened. he took the survey without login in. i think that is the answer. thanks for the solution. think i can close this.

**Comment by rafaelbn** [comment]
:+1:
